//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class Trust_351st_Fac {
        displayName = "[351st Legion] Evarrian Company";
        side = 1;
        flag = "";
        icon = "";
        priority = 2;
    };
};

class CfgGroups {
    class WEST {

        class Trust_351st_Fac {
            name = "[351st Legion] Evarrian Company";

            class Infantry {
                name = "Infantry";

                class b_trust351stfac_infantry_squad {
                    name = "Squad";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_Squadleader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Teamleader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_AutoRifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_AT_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Medic_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                };

                class b_trust351stfac_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_Teamleader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_AutoRifleman_01";
                    };
                };

                class b_trust351stfac_infantry_engineer_team {
                    name = "Engineer Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_Engineer_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Engineer_01";
                    };
                };

                class b_trust351stfac_infantry_at_team {
                    name = "AT Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_Teamleader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_AT_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_AT_Rifleman_01";
                    };
                };

                class b_trust351stfac_infantry_sentry_team {
                    name = "Sentry Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_Rifleman_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

                class b_trust351stfac_specops_arf_team {
                    name = "ARF Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_NCO_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_Trooper_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_Marksman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_Medic_01";
                    };
                };

                class b_trust351stfac_specops_arf_recon_team {
                    name = "ARF Recon Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_NCO_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARF_Marksman_01";
                    };
                };

                class b_trust351stfac_specops_arc_team {
                    name = "ARC Team";
                    side = 1;
                    faction = "trust_351st_fac";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARC_Trooper_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARC_Trooper_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARC_Trooper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Trust351stFac_ARC_Trooper_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_engineer_F;
    class B_engineer_F_OCimport_01 : B_engineer_F { scope = 0; class EventHandlers; };
    class B_engineer_F_OCimport_02 : B_engineer_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };

    class B_recon_TL_F;
    class B_recon_TL_F_OCimport_01 : B_recon_TL_F { scope = 0; class EventHandlers; };
    class B_recon_TL_F_OCimport_02 : B_recon_TL_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_SL_F;
    class B_Soldier_SL_F_OCimport_01 : B_Soldier_SL_F { scope = 0; class EventHandlers; };
    class B_Soldier_SL_F_OCimport_02 : B_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_GL_F;
    class B_Soldier_GL_F_OCimport_01 : B_Soldier_GL_F { scope = 0; class EventHandlers; };
    class B_Soldier_GL_F_OCimport_02 : B_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class B_soldier_AAR_F;
    class B_soldier_AAR_F_OCimport_01 : B_soldier_AAR_F { scope = 0; class EventHandlers; };
    class B_soldier_AAR_F_OCimport_02 : B_soldier_AAR_F_OCimport_01 { class EventHandlers; };


    class B_Trust351stFac_Engineer_01 : B_engineer_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_CEE_Engineer_Vest","Trust_gar_ENG_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_CEE_Engineer_Vest","Trust_gar_ENG_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15S","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};

        backpack = "Trust_EOD_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",3,10}}},{"SWLB_CEE_Engineer_Vest",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_EOD_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_ENG_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_Rifleman_01 : B_Soldier_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15S","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};

        backpack = "Trust_clone_bags";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",3,10}}},{"SWLB_clone_specialist_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_clone_bags",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_phase2_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_AT_Rifleman_01 : B_Trust351stFac_Rifleman_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Rifleman";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15S","ls_weapon_rps6","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","ls_weapon_rps6","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","ls_mag_rpg_1rnd","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","ls_mag_rpg_1rnd","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};

        backpack = "Trust_Heavy_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{"JLTS_stun_mag_short",10},""},{"ls_weapon_rps6","","","",{"ls_mag_rpg_1rnd",1},{},""},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",2,10},{"ls_mag_rpg_1rnd",1,1}}},{"SWLB_clone_specialist_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1},{"ls_mag_rpg_1rnd",1,1}}},{"Trust_Heavy_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10},{"ls_mag_rpg_1rnd",1,1}}},"Trust_gar_phase2_helmet","G_Combat",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_ARF_Trooper_01 : B_recon_TL_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARF Trooper";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};

        backpack = "Trust_Clone_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15A_plastic","","","",{"JLTS_DC15A_mag",60},{"JLTS_stun_mag_short",10},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",3,60},{"JLTS_stun_mag_short",2,10}}},{"SWLB_CEE_ARF_Vest",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_Clone_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_ARF_helmet","G_Combat",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_ARF_NCO_01 : B_Trust351stFac_ARF_Trooper_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARF NCO";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_NCO_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_NCO_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15S","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};

        backpack = "Trust_Recon_RTO_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",2,10}}},{"SWLB_CEE_ARF_Vest",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_Recon_RTO_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_NCO_ARF_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_ARF_Marksman_01 : B_Trust351stFac_ARF_Trooper_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARF Marksman";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"SWLB_CEE_ARF_Vest","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15X","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15X","SWLW_DC17"};

        magazines[] = {"JLTS_DC15X_mag","SWLW_DC17_Mag","JLTS_DC15X_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15X_mag","SWLW_DC17_Mag","JLTS_DC15X_mag","SWLW_DC17_Mag"};

        backpack = "Trust_clone_bags";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15X","","","JLTS_DC15X_scope",{"JLTS_DC15X_mag",15},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15X_mag",3,15}}},{"SWLB_CEE_ARF_Vest",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_clone_bags",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_ARF_helmet","G_Combat",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_ARF_Medic_01 : B_Trust351stFac_ARF_Trooper_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARF Medic";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Medic_uniform";

        linkedItems[] = {"SWLB_clone_medic_armor","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"SWLB_clone_medic_armor","Trust_gar_ARF_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};

        weapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};

        backpack = "Trust_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15A_plastic","","","",{"JLTS_DC15A_mag",60},{"JLTS_stun_mag_short",10},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Medic_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",3,60},{"JLTS_stun_mag_short",2,10}}},{"SWLB_clone_medic_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_ARF_helmet","G_Combat",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_ARC_Trooper_01 : B_Trust351stFac_ARF_Trooper_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARC Trooper";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_arc_armor","Trust_gar_Base_ARF","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"SWLB_clone_arc_armor","Trust_gar_Base_ARF","ItemMap","SWLB_comlink","ItemCompass","ItemWatch"};

        weapons[] = {"3AS_WestarM5_F","SWLW_DC17"};
        respawnWeapons[] = {"3AS_WestarM5_F","SWLW_DC17"};

        magazines[] = {"3AS_60Rnd_EC50_Mag","SWLW_DC17_Mag","3AS_60Rnd_EC50_Mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"3AS_60Rnd_EC50_Mag","SWLW_DC17_Mag","3AS_60Rnd_EC50_Mag","SWLW_DC17_Mag"};

        backpack = "SWLB_clone_arc_backpack";

        ALiVE_orbatCreator_loadout[] = {{"3AS_WestarM5_F","","","3AS_Optic_Scope_WestarM5",{"3AS_60Rnd_EC50_Mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"3AS_60Rnd_EC50_Mag",3,60}}},{"SWLB_clone_arc_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"SWLB_clone_arc_backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_Base_ARF","G_Combat",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_Squadleader_01 : B_Soldier_SL_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squadleader";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_NCO_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_specialist_armor","Trust_gar_NCO_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15S","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};

        backpack = "Trust_Recon_RTO_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",3,10}}},{"SWLB_clone_specialist_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_Recon_RTO_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_NCO_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_Teamleader_01 : B_Trust351stFac_Rifleman_01 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Teamleader";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_assault_armor","Trust_gar_phase2_Vet_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_assault_armor","Trust_gar_phase2_Vet_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15A_plastic","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag","JLTS_DC15A_mag","JLTS_stun_mag_short","SWLW_DC17_Mag"};

        backpack = "Trust_Clone_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15A_plastic","","","",{"JLTS_DC15A_mag",60},{"JLTS_stun_mag_short",10},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",3,60},{"JLTS_stun_mag_short",3,10}}},{"SWLB_clone_assault_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_Clone_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_phase2_Vet_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_Grenadier_01 : B_Soldier_GL_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"SWLB_clone_grenadier_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_grenadier_armor","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15A_ugl_plastic","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15A_ugl_plastic","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","1Rnd_HE_Grenade_shell","SWLW_DC17_Mag","JLTS_DC15A_mag","1Rnd_HE_Grenade_shell","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","1Rnd_HE_Grenade_shell","SWLW_DC17_Mag","JLTS_DC15A_mag","1Rnd_HE_Grenade_shell","SWLW_DC17_Mag"};

        backpack = "Trust_clone_bags";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15A_ugl_plastic","","","",{"JLTS_DC15A_mag",60},{"1Rnd_HE_Grenade_shell",1},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",3,60},{"1Rnd_HE_Grenade_shell",3,1}}},{"SWLB_clone_grenadier_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_clone_bags",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_phase2_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_AutoRifleman_01 : B_soldier_AAR_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "AutoRifleman";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Phase2_uniform";

        linkedItems[] = {"ls_gar_heavy_vest","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"ls_gar_heavy_vest","Trust_gar_phase2_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_Z6","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_Z6","SWLW_DC17"};

        magazines[] = {"JLTS_Z6_mag","SWLW_DC17_Mag","JLTS_Z6_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_Z6_mag","SWLW_DC17_Mag","JLTS_Z6_mag","SWLW_DC17_Mag"};

        backpack = "Trust_Clone_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_Z6","","","",{"JLTS_Z6_mag",300},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Phase2_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_Z6_mag",3,300}}},{"ls_gar_heavy_vest",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_Clone_Backpack",{{"FirstAidKit",3},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_phase2_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_Trust351stFac_Medic_01 : B_Soldier_F_OCimport_02 {
        author = "M/CS-1028 ""Trustful""";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "trust_351st_fac";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "Trust_gar_Medic_uniform";

        linkedItems[] = {"SWLB_clone_medic_armor","Trust_gar_Medic_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};
        respawnlinkedItems[] = {"SWLB_clone_medic_armor","Trust_gar_Medic_helmet","ItemMap","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"};

        weapons[] = {"JLTS_DC15S","SWLW_DC17"};
        respawnWeapons[] = {"JLTS_DC15S","SWLW_DC17"};

        magazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};
        respawnMagazines[] = {"JLTS_DC15A_mag","SWLW_DC17_Mag","JLTS_DC15A_mag","SWLW_DC17_Mag"};

        backpack = "Trust_backpack";

        ALiVE_orbatCreator_loadout[] = {{"JLTS_DC15S","","","",{"JLTS_DC15A_mag",60},{},""},{},{"SWLW_DC17","","","",{"SWLW_DC17_Mag",20},{},""},{"Trust_gar_Medic_uniform",{{"FirstAidKit",3},{"ACE_EarPlugs",1},{"SWLW_DC17_Mag",2,20},{"SWLW_beltGrenade_mag",1,1},{"JLTS_DC15A_mag",6,60},{"JLTS_stun_mag_short",3,10}}},{"SWLB_clone_medic_armor",{{"SWLW_beltGrenade_mag",1,1},{"SmokeShell",2,1},{"Chemlight_green",1,1}}},{"Trust_backpack",{{"FirstAidKit",3},{"ACE_surgicalKit",1},{"SWLW_mag_40mm_10rnd",2,10}}},"Trust_gar_Medic_helmet","",{},{"ItemMap","","SWLB_comlink","ItemCompass","ItemWatch","JLTS_NVG_droid_chip_1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};